### ISSUE TITLE
Cannot find ElevenLabs API key

### ISSUE THREAD

**Issue by dadaewqq** [cogentapps/chat-with-gpt#1]
I cannot find ElevenLabs API key, it shows xi-api-key is in the 'Profile' tab on https://beta.elevenlabs.io. But the 'Profile' tab doesn't exist.

**Comment by cogentapps** [comment]
Click your avatar (or initials) in the top right of the Eleven Labs website, Profile is one of the options under the menu that appears. Your API key should be right at the top of the Profile page.

I’ll make it more clear in the app.

**Comment by catgirl69** [comment]
haha
