### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by Mikyner** [cogentapps/chat-with-gpt#104]
docker run -v $(pwd)/data:/app/data -p 3003:3000 ghcr.io/cogentapps/chat-with-gpt:release
Unable to find image 'ghcr.io/cogentapps/chat-with-gpt:release' locally
release: Pulling from cogentapps/chat-with-gpt
63b65145d645: Pull complete
bc59db64d63d: Pull complete
c8fd6d18c4a0: Pull complete
eb563838426b: Pull complete
06c6bcf0f0eb: Pull complete
d58b902867ad: Pull complete
f0e7e688716c: Pull complete
ebede05b6017: Pull complete
511deccdd15b: Pull complete
55364b240ecf: Pull complete
c363fe49e713: Pull complete
e0e18c2c0d2b: Pull complete
29d6d12e1f51: Pull complete
Digest: sha256:4540a1c8e39fa4cecb6b51682a1117c29fb3df6d940198a6b28953a1b7f06527
Status: Downloaded newer image for ghcr.io/cogentapps/chat-with-gpt:release
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error

**Comment by cogentapps** [comment]
Hello, ARM support (for Raspberry Pi etc.) is not currently available, but I'm looking to add it soon.

See also: https://github.com/cogentapps/chat-with-gpt/issues/40
