### ISSUE TITLE
ETA on hands-free conversation feature?

### ISSUE THREAD

**Issue by Arche151** [cogentapps/chat-with-gpt#108]
Dear cogentapps,

I wanted to take a moment to thank you for developing such a remarkable app. Your hard work is much appreciated! 

During our last communication a few weeks ago, you mentioned that there are plans to implement the ability to have a hands-free conversation with ChatGPT. I was wondering if there are any updates on when this feature will be available.

Additionally, I was curious to know whether there are any plans to include the ability to use a custom cloned ElevenLabs voice?

Thank you for considering my questions. Looking forward to hearing from you.

Best Regards!

**Comment by cogentapps** [comment]
As of today, you can enable autoplay for text-to-speech under Settings!

For a fully hands-free experience, you will also need speech recognition to start automatically. This isn't implemented yet, and I don't have a timeline to give you, but it's on the roadmap! (If anyone else wants to try building this feature, PRs are welcome.)

**Comment by Arche151** [comment]
So cool, thanks!! Unfortunately I don't see the setting though. I just updated the docker immage, but can't find the setting to enable autoplay for tts.

**Comment by cogentapps** [comment]
If your update was successful, there will be a new option on the settings screen under "Speech" called "Read messages aloud automatically":

![Screenshot 2023-04-15 6 15 29 AM](https://user-images.githubusercontent.com/127109874/232226140-49893101-af53-4d9a-96e0-cba0e92ca8b6.png)

**Comment by Arche151** [comment]
It works now! Dude, you're amazing. Thank you again :)
