### ISSUE TITLE
plugins integration suggestion

### ISSUE THREAD

**Issue by Lionardo** [cogentapps/chat-with-gpt#110]
hej @cogentapps love your chatgpt project!👏
How about integrating getitAI's open Plugin Store for easy plugin installs? (https://www.getit.ai/gpt-plugins) Let's chat for 15 mins: https://calendly.com/d/z4j-cb5-h2y/getitai-devs

**Comment by cogentapps** [comment]
Some additional work is needed to make ChatGPT plugins work with Chat with GPT.

It's on my roadmap, once a working version is ready, I'll take another look at this.
