### ISSUE TITLE
config.yml doesn't work at all

### ISSUE THREAD

**Issue by Arche151** [cogentapps/chat-with-gpt#117]
Unfortunately, creating a `config.yml` file in my `data` directory to that my API keys are saved, doesn't work for me. 

It's really weird: When writing a message into the chat, OpenAI responds with the error, that I sent a false API and shows me that it received the 11Labs API from my `config.yml`, instead of the OpenAI API. I double checked that I entered it correctly and didn't mix anything up. 

The 11Labs API is also not loaded correctly, because the app just get's stuck at loading when I press `play` next to a message.

When I checked my settings, the keys also weren't visible. When I manually entered them, everything worked again.

**Comment by megavenik** [comment]
@Arche151 hi! I'm facing the same issue, can you please tell, how did you fix it on your side?
