### ISSUE TITLE
No "data" directory to put config.yaml file in

### ISSUE THREAD

**Issue by Arche151** [cogentapps/chat-with-gpt#135]
There used to be a data directory in the apps main directory, but after I updated it, it's gone.

Where do I put the config.yaml file now? I put it in the main directory but when starting chat with gpt, it didn't load the config unfortunately.

**Comment by cogentapps** [comment]
When using the Docker command from the instructions,

`docker run -v $(pwd)/data:/app/data -p 3000:3000 ghcr.io/cogentapps/chat-with-gpt:release`

This part here:

`-v $(pwd)/data:/app/data`

tells Docker to look for a folder called `data` inside the current folder ('pwd' is wherever you are running the command from). If the folder doesn't exist, Docker will create it for you on the first run, but you can create it yourself and place the config.yaml file inside.

**Comment by Arche151** [comment]
Ahh ok, thanks for explaining!
