### ISSUE TITLE
[Feature Request] Set GPT-4 as default

### ISSUE THREAD

**Issue by CyrisXD** [cogentapps/chat-with-gpt#140]
Is there a way to set GPT-4 as default on new conversations?
Would be great to have this. 

Cheers

**Comment by fishwarp** [comment]
Yes, noting even when set, to GPT-4, the Chat setting reverts to GPT-3.5-turbo.  Would be a useful feature to allow the selected engine to be perm.  Thanks

**Comment by mikethm** [comment]
this appears to have recently been broken - 2 weeks ago it preserved the setting...

**Comment by BongoCaat** [comment]
> this appears to have recently been broken - a few weeks ago it preserved the setting...

It's because now they're saved but in the chat not in all the website.

**Comment by cogentapps** [comment]
Should be fixed now.
