### ISSUE TITLE
Docker image is huge, optimization needed

### ISSUE THREAD

**Issue by rounakdatta** [cogentapps/chat-with-gpt#143]
Hello again!

The size of the Docker image is huge (about 3GB). I think we can do obvious optimizations to bring down the size. Even I get an occasional OOM when running the container with lower resources. I believe the app shouldn't be that memory-heavy as well right?

**Comment by crim50n** [comment]
I am also interested in this question. https://github.com/crim50n/ChatGPT-Next-Web has almost the same functionality (no voice synthesizer) and takes 285 MB.

**Comment by aadityabhatia** [comment]
Agreed. Why use `node:19-bullseye-slim` instead of `node:alpine` as the base?

**Comment by cogentapps** [comment]
Resolved.
