### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by JHK** [cogentapps/chat-with-gpt#147]
This allows to "install" the chat bot as a system application. Personally I make use of PWAs whenver possible. This would also make this app a contender to pure desktop applications.

**Comment by aadityabhatia** [comment]
@JHK excellent idea. Any particular resources to help setup a PWA? There is already a [manifest.json](https://github.com/cogentapps/chat-with-gpt/blob/main/app/public/manifest.json). Guessing we need a service worker. What else?
