### ISSUE TITLE
GPT4 api key error

### ISSUE THREAD

**Issue by bleetube** [cogentapps/chat-with-gpt#152]
When attempting to use GPT4 on my self-hosted instance or chatwithgpt.ai, it responds with: 
 > I'm sorry, I'm having trouble connecting to OpenAI (The model: gpt-4 does not exist). Please make sure you've entered your OpenAI API key correctly and try again.

Chromium console shows `Failed to load resource: the server responded with a status of 404 ()` on `api.openai.com/v1/chat/completions:1`

I'm guessing there might be a simple explanation here, but I'm not seeing any reference to this error in the repo yet.  Any advice?

I have the OpenAI subscription and use GPT-4 on the official web interface, so I'm not sure why I'm seeing this error. The OpenAI billing platform does show my usage from using GPT3.5 with the same api key with my self-hosted chat-with-gpt instance.

**Comment by cogentapps** [comment]
Your ChatGPT Plus subscription only gives you access to GPT-4 through the official app, unfortunately. API access (needed for other apps) requires a beta invite.
