### ISSUE TITLE
How to use gpt-3.5-turbo-16k?

### ISSUE THREAD

**Issue by jtrein** [cogentapps/chat-with-gpt#154]
How do we switch to use the `gpt-3.5-turbo-16k` model?

**Comment by cogentapps** [comment]
Added as an option along with GPT4 32K and the snapshot models.

**Comment by jtrein** [comment]
Thank you gud ser

**Comment by joboyx** [comment]
Is this still true after this announcement?

https://openai.com/blog/gpt-4-api-general-availability

I still can't use GPT4.

**Comment by joboyx** [comment]
Looks like they've only provided access to previously billed and paying customers of OpenAI API key.

https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
