### ISSUE TITLE
How can I self-host this project.

### ISSUE THREAD

**Issue by xfdywy** [cogentapps/chat-with-gpt#2]
Hi, thanks for your great project. If I want to host this project in my only server, what should I do? Is there any document I can refer to?

**Comment by juangf7** [comment]
https://www.reddit.com/r/OpenAI/comments/11k19en/comment/jb6rhay/?utm_source=share&utm_medium=web2x&context=3

**Comment by cogentapps** [comment]
Hi, I added instructions for running the app locally to the README.
