### ISSUE TITLE
Automatic playback of text-to-speech

### ISSUE THREAD

**Issue by gorfreed** [cogentapps/chat-with-gpt#21]
Why do users manually need to trigger the voice response generated with the ElevenLabs speech API? The whole idea to have it is to make the chat experience more organic, so if a user has activated the API in their settings, shouldn't voice responses be played automatically or is this due to some technical limitation?

**Comment by cogentapps** [comment]
Agree this is needed, will add it as an option.

**Comment by cogentapps** [comment]
TTS autoplay is now available for self-hosted users and on the [new domain](https://www.chatwithgpt.ai).
