### ISSUE TITLE
Which version gpt be used?

### ISSUE THREAD

**Issue by khairulimran-97** [cogentapps/chat-with-gpt#25]
Which version of gpt api be used for this? Can support gpt-4 later?

**Comment by cogentapps** [comment]
ChatGPT Turbo, which is GPT 3.5.

As far as I can tell from the docs (I don't have access yet), GPT-4 uses the exact same API as ChatGPT Turbo, so I'll look at adding an option to switch to GPT-4 if you have access.

**Comment by cogentapps** [comment]
Added in https://github.com/cogentapps/chat-with-gpt/pull/33, but only works if you have a GPT-4 invite.
