### ISSUE TITLE
GPT4 ? 

### ISSUE THREAD

**Issue by arthurmougin** [cogentapps/chat-with-gpt#27]
Interested in adding support for gpt4?

**Comment by nirav72** [comment]
OpenAI has not made gpt4 API available for general use yet. You can use gpt 4 if you have Chatgpt plus subscription. But you'll have to use the web UI or one of the many other opensourced  chatgpt desktop clients out there.

**Comment by schmidp** [comment]
I created a branch here that allows setting the model name: https://github.com/openresearch/chat-with-gpt/tree/feature/specify_model

but since I have no access to gpt-4 I can't test it.

ps: I am also not a web dev and never done anything in react so....

**Comment by cogentapps** [comment]
@schmidp feel free to open a PR for that, I was given access to GPT-4 this morning so I will check it out.

**Comment by cogentapps** [comment]
Added in https://github.com/cogentapps/chat-with-gpt/pull/33, only works if you have a GPT-4 invite.
