### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by rounakdatta** [cogentapps/chat-with-gpt#29]
Hello, impressive project! Your project is getting a lot of traction and many folks would be interested in self-hosting it. You already have the Dockerfile ready, would you mind publishing a public Docker image which people can _just_ pull? I think a GitHub action like [this](https://github.com/0xERR0R/bitwarden-backup-docker/blob/main/.github/workflows/build.yaml) would suffice.

Thanks!

**Comment by cogentapps** [comment]
Added in https://github.com/cogentapps/chat-with-gpt/pull/30:

```
docker run -v $(pwd)/data:/app/data -p 3000:3000 ghcr.io/cogentapps/chat-with-gpt:release
```
