### ISSUE TITLE
Support for displaying the SVGs generated?

### ISSUE THREAD

**Issue by rounakdatta** [cogentapps/chat-with-gpt#34]
https://www.reddit.com/r/ChatGPT/comments/11hgtrk/chatgpt_can_generate_simple_images_via_svg/

Often ChatGPT can produce the SVG code for simple images. We can render them in the UI. I've also noticed that ChatGPT can sometimes provide Imgur links, but they rarely work.

**Comment by cogentapps** [comment]
Added!

https://chatwithgpt.netlify.app/s/jNYBH/creating-an-svg-illustration-of-the-moon

**Comment by rounakdatta** [comment]
Your speed of execution is unmatched! :rocket:
