### ISSUE TITLE
Unable to sync even after logging in 

### ISSUE THREAD

**Issue by iribarrenjg** [cogentapps/chat-with-gpt#38]
I have created a user, it registered well. 

I can login from different browsers/machines but it is not remembering my API key, nor my prompt. 

I think it should definitely be remembering the API, I can see it does store the information within the cookies but not with the created user. 

Also would be nice to be able to delete chats. 

Great work so far, love it.

**Comment by khairulimran-97** [comment]
Me too. I using self host docker. The sign in show error login. My previous messages not show also.
