### ISSUE TITLE
Unable to copy full markdown code

### ISSUE THREAD

**Issue by vesector** [cogentapps/chat-with-gpt#43]
Hello, 

When attempting to copy the code after it is presented (clicking on the copy option) it is not copying to clipboard. 

Tested on different machines Win/MacOSx and Safari, Firefox, Chrome and Edge.

**Comment by cogentapps** [comment]
Hello, I am looking into this - a couple quick questions:
- Is this happening when you're copying a code block, or a whole message?
- Does it happen with any message or just one in particular?
