### ISSUE TITLE
GPT-4 api

### ISSUE THREAD

**Issue by icemunk** [cogentapps/chat-with-gpt#44]
Any plans to update to use the GPT-4 API as an option? Or the other engines?

**Comment by thevolcanomanishere** [comment]
If you check settings you can see that there is a model selection drop-down.

**Comment by initmaks** [comment]
GPT-4 option is already available, check the Model dropdown menu in the Settings (it only works if you got your invite).
![CleanShot 2023-03-17 at 14 24 41](https://user-images.githubusercontent.com/9087436/225987757-a05c1aca-c524-4981-86a9-98efa5289310.png)

**Comment by icemunk** [comment]
Great, thanks - That's much easier the modifying the openai.ts file :) I just needed to run the latest branch
