### ISSUE TITLE
Add OpenAI Whisper Input

### ISSUE THREAD

**Issue by tjhubz** [cogentapps/chat-with-gpt#61]
I think it would be really cool if [OpenAI's whisper](https://github.com/openai/whisper) could be used as an input method for text if possible. 

Currently using the tool for case interviews and think it would be really helpful if I could evaluate my spoken responses. Could be a cool way to interact with the GPT API!

**Comment by tluyben** [comment]
I added this here : https://github.com/cogentapps/chat-with-gpt/pull/58

It has browser speech recognition as well as Whisper and you can switch between them.
