### ISSUE TITLE
STT doesn't work, Website doesn't work on Firefox anymore

### ISSUE THREAD

**Issue by Arche151** [cogentapps/chat-with-gpt#69]
Hey!

I was super excited to see that Whisper is now integrated into this remarkable app. But unfortunately the website doesn't work on Firefox Desktop (macOS) anymore. It just gets stuck at the three pulsating blue dots indicating a loading process. The same problem occurs when using Firefox for Android. 

When using a Chromium-based browser, the website loads fine. 

Also, I cannot get the speech recognition to work :( Neither on Chrome for Desktop (macOS) nor on Chrome for Android. When clicking the microphone button, the website asks for access to my microphone, which I grant it. Then the microphone turns red, indicating that it is recording, but nothing happens.

No text is being written into the text field, so I thought maybe it's just not visible, but just pressing send after speaking also doesn't work.

**Comment by fdb** [comment]
Can confirm. I get the following error in the console:

```
Uncaught ReferenceError: webkitSpeechRecognition is not defined
    <anonymous> https://chatwithgpt.netlify.app/static/js/main.63992e72.js:2
    <anonymous> https://chatwithgpt.netlify.app/static/js/main.63992e72.js:2
    <anonymous> https://chatwithgpt.netlify.app/static/js/main.63992e72.js:2
```

**Comment by tjhubz** [comment]
Can confirm the issue exists on Firefox for Windows 10 as well.

**Comment by Arche151** [comment]
Firefox works now again!
