### ISSUE TITLE
requeset

### ISSUE THREAD

**Issue by jordon31** [cogentapps/chat-with-gpt#76]
Elimination (single chat)

Add the new GPT-4 models to me I need from 32K tokens

add an .env file to add the APIs

**Comment by cogentapps** [comment]
- delete is available on each chat in the sidebar
- you can now put your API keys in a config file, see here: https://github.com/cogentapps/chat-with-gpt/issues/97#issuecomment-1509752565
- GPT-4 8K is available if your account is approved. I'll look at adding the 32K version too, for the lucky ones with access.
