### ISSUE TITLE
store API keys in account settings, not cookie

### ISSUE THREAD

**Issue by occasionallydavid** [cogentapps/chat-with-gpt#77]
I lose my API keys every time I close my tab (self-destructing cookies). I'd like to setup some accounts for family that are preconfigured. Would it be possible to move API keys into backend storage rather than cookie

**Comment by occasionallydavid** [comment]
It's a really nice project, a little shame it requires a tech user to set it up though :/

I think conversation history is also somehow related to session? I can see chats in SQLite, but the left tab does not populate with my old chats after login either

**Comment by Frajder** [comment]
Storing the API key in a .env file is not a good idea since the app supports multiple users.

**Comment by iloahz** [comment]
my use case is family sharing too, adding api key every time is not convenience and even a blocker for non-tech users, I just want to setup a out-of-the-box chatgpt that everyone in the family can instantly explore, even if it compromises the multi-user feature

**Comment by GOvEy1nw** [comment]
Yes I agree, an option to support multiple users (login) using the same API key would be great.

**Comment by occasionallydavid** [comment]
just FYI https://github.com/mckaywrigley/chatbot-ui allows setting the key in the backend. Only "problem" is it's a next.js app that seems to think it's okay to send 1MB of JS and fonts to the client for such a simple app, and streaming doesn't seem to work properly in Firefox (but it's fine in Chrome derivs)

**Comment by SimonMacIntyre** [comment]
In my case, as an exclusive local docker use only, it would be ideal to bootstrap the container with my API key. It won't have other users, ever. 

Maybe if an env variable is present it can be automatically set?

In the same vein, I'd love to preset the model to use 4, but thats far less important. Bootstrapping the api key is crucial, its so tedious for docker users.

**Comment by cogentapps** [comment]
Added for self-hosters:

https://github.com/cogentapps/chat-with-gpt#store-your-api-keys-on-the-server
