### ISSUE TITLE
It's great! But why not make it autopaly 

### ISSUE THREAD

**Issue by weidutech** [cogentapps/chat-with-gpt#81]
Why not make the conversation continue, you need to manually click to play the voice. I think I am going to modify the code by myself.

**Comment by weidutech** [comment]
I mean, let GPT reply me directly with voice, ElevenLabs API is very good, but every time I have to click to get the voice, if GPT reply me directly from text to voice, it will have more artificial intelligence feeling, just like the scene in the movie <her>.

**Comment by weidutech** [comment]
I change the onClickCapture to OnLoad in line 273:  <Button variant="subtle" size="sm" compact onLoad={onClick} loading={status === 'init'}> but it didn't  work. How to fix it? I'm not a pro in typescript, sry for that.

**Comment by cogentapps** [comment]
This is coming, along with other TTS options.

**Comment by weidutech** [comment]
> This is coming, along with other TTS options.

very excited, btw we can remove the input bar, only use voice input, and VAD technology and so on, It is going to be the greatest GPT ever!

**Comment by kotobuki09** [comment]
> This is coming, along with other TTS options.

Thank you for the updated news! Exciting for the next version

**Comment by aodrasa** [comment]
Would also love for the speech input to be sent automatically (like siri, alexa etc). Any plans for that? Great job so far!

**Comment by dawid-abastr** [comment]
Please, add this feature, it would be a game-changer! The same with voice recognition - it should automatically send the message after finishing speaking -  the same as in bing chat.

**Comment by kotobuki09** [comment]
Have anyone made a change and updated this feature yet?

**Comment by Vuthric** [comment]
also waiting!

**Comment by weidutech** [comment]
> 

I’m still waiting

**Comment by weidutech** [comment]
> This is coming, along with other TTS options.

I'm still waiting

**Comment by cogentapps** [comment]
TTS autoplay is now available for self-hosted users and on the [new domain](https://www.chatwithgpt.ai/).
