### ISSUE TITLE
Custom cloned voice 

### ISSUE THREAD

**Issue by wyhauyeung** [cogentapps/chat-with-gpt#86]
Is there a way I can choose custom cloned voice I made in eleven labs?

**Comment by ghgoodreau** [comment]
@wyhauyeung As a quick fix, if you are running this locally with npm, you can add your custom cloned voice to app/src/tts/defaults.ts. Here is an example snippet:

```ts
export const defaultVoiceList = [
    {
        "voice_id": "Enter custom voice ID here",
        "name": "Enter custom name here",
        "preview_url": "", // this can be blank, the preview button just won't do anything.
    },
    {
        "voice_id": "21m00Tcm4TlvDq8ikWAM",
        "name": "Rachel",
        "preview_url": "https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/6edb9076-c3e4-420c-b6ab-11d43fe341c8.mp3",
    },
````

This will then show up in the voice select dropdown. If you then select your custom cloned voice, it will work properly.

I don't have the bandwidth to make an actual PR for this but a suggested change for anyone reading would be to either add an input field for these custom voices that adds to this array, or have this file pull the custom voices from https://api.elevenlabs.io/docs#/voices/Get_voices_v1_voices_get.

**Comment by cogentapps** [comment]
Today's update adds a "Custom Voice" option on the ElevenLabs voice dropdown, which you can use to select a custom voice from your account.

Let me know if you have any issues making it work.

**Comment by Tobe2d** [comment]
It is not saving the vocie ID
![image](https://github.com/cogentapps/chat-with-gpt/assets/4099839/cc0beeb6-fc31-4b7f-97ee-135f91ddc6ff)
When I try ading the voice id and hit save nothing happens. and when I open settings again in the same session it is empty again
