### ISSUE TITLE
why nessus service

### ISSUE THREAD

**Issue by Yaoxiao1** [cogentapps/chat-with-gpt#89]
I cloned this repo and build a local docker image, after running it with `-p 3001:3000` 
I use `nmap localhost` and find the servcie name of this port is nessus,
```
PORT      STATE SERVICE  
22/tcp    open  ssh  
80/tcp    open  http  
3001/tcp  open  nessus  
```
I just wonder why this service, because I scan all the code and not found anything about nessus

**Comment by cogentapps** [comment]
nmap is just guessing the name of the service from the port number, since you’re running the app on a port more commonly used by another application (nessus).
