### ISSUE TITLE
Native Chrome google voices for TTS ?

### ISSUE THREAD

**Issue by magicmars35** [cogentapps/chat-with-gpt#95]
Is it possible to use TTS google chrome API native voices,  instead of ElevenLabs Ones ?
(like google chrome ext. plugin talk-to-chatGPT)
https://www.google.com/intl/en/chrome/demos/speech.html

**Comment by cogentapps** [comment]
Today's update adds an option to use your browser's built-in text-to-speech for free.

Also, the code has been improved to make it easy to add other TTS options in the future.

If you encounter any issues using this new feature, please open a separate issue.
