### ISSUE TITLE
Audio Input not working. Error: "Sorry, an error occured trying to record audio."

### ISSUE THREAD

**Issue by jlar0che** [cogentapps/chat-with-gpt#99]
**Issue**
Unable to use audio input. Receiving the following error message: "Sorry, an error occured trying to record audio." 

_Here is a screenshot:_
![image](https://picsur.home-lab.site/i/99d5eaff-11f7-4500-9580-a0133c1156bb.jpg)

**What I tried / Looked at / What I Made sure:**

1. Made sure my audio input device was properly detected in my OS.
2. Tested Audio Input Device
3. Made sure my ChatGPT and ElevenLabs APIs were properly input and were correct 
4. Tried restarting the Docker container

**Environment Details:**
- Installed on Synology NAS via Docker.
- Synology DS1517+
- Desktop OS: Windows 10 64bit

**Comment by kamil-malinski** [comment]
you need to use https for the voice recognition to work

**Comment by jlar0che** [comment]
Thanks. I setup a reverse proxy for internal use and the error goes away. Still have a question though. I hope I'm not overlooking something obvious, but the mic turns red when I click it (activated?) and I am prompted to give access to my microphone device. I click in the affermative and there is no prompt so I assume I just start talking and the conversion should happen. It does not. I click on the mic icon again to stop the recording and again, no text is entered into the textbox.

**Comment by kamil-malinski** [comment]
it should work like that (it does for me with an iPhone)... what device/browser are you using?

**Comment by jlar0che** [comment]
Windows 10 64bit (Version 10.0.19045 Build 19045)
Firefox 111.0.1 (64bit)

**NOTE:**
I just tested it in Google Chrome Version 111.0.5563.147 (32-bit) and it worked...

**Comment by cogentapps** [comment]
> Thanks. I setup a reverse proxy for internal use and the error goes away. Still have a question though. I hope I'm not overlooking something obvious, but the mic turns red when I click it (activated?) and I am prompted to give access to my microphone device. I click in the affermative and there is no prompt so I assume I just start talking and the conversion should happen. It does not. I click on the mic icon again to stop the recording and again, no text is entered into the textbox.

Thanks for reporting, sounds like a browser compatibility issue!
